version: '3.8'

services:
  vocab-api:
    build: .
    container_name: vocabstack_backend
    ports:
      - "8000:8000"
    volumes:
      # Mapeia o banco de dados para fora do container para persistência
      - ./data:/app/data
    environment:
      # Variável de ambiente para o código saber onde salvar o DB
      - DATABASE_URL=/app/data/vocabstack.db
    restart: always
    user: "1000:1000" # Define um usuário não privilegiado para evitar problemas de permissão no ZimaOS
    networks:
      - vocab-network

  nginx:
    image: nginx:latest
    container_name: vocabstack_frontend
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vocab-api
    restart: always
    networks:
      - vocab-network

networks:
  vocab-network:
    driver: bridge
